### ISSUE TITLE
Resolve bigger request payload error

### ISSUE THREAD

**Issue by tpichlak** [carldata/borsuk#57]
This happens when making request for autoii/fit endpoint while using whole channels.

My guess is that one of this arrays is to big to parse with current settings.
The payload is constructed like this:
`val payload = HttpEntity(ContentTypes.`application/json`, FitAutoIIParams(startDate,
        time.Duration.ofHours(24), flow, rainfall, Array(60, 120, 480), time.Duration.ofHours(24),
        time.Duration.ofHours(24), time.Duration.ofHours(24)).toJson.compactPrint)`

`[ERROR] [09/21/2018 08:53:31.966] [borsuk-akka.actor.default-dispatcher-4] [akka://borsuk/system/StreamSupervisor-0/flow-2-0-headSink] Error during preStart in [akka.http.scaladsl.model.HttpEntity$Limitable@57ae4e0e]: EntityStreamSizeException: actual entity size (Some(11933835)) exceeded content length limit (8388608 bytes)! You can configure this by setting `akka.http.[server|client].parsing.max-content-length` or calling `HttpEntity.withSizeLimit` before materializing the dataBytes stream.
EntityStreamSizeException: actual entity size (Some(11933835)) exceeded content length limit (8388608 bytes)! You can configure this by setting `akka.http.[server|client].parsing.max-content-length` or calling `HttpEntity.withSizeLimit` before materializing the dataBytes stream.
        at akka.http.scaladsl.model.HttpEntity$Limitable$$anon$1.preStart(HttpEntity.scala:612)
        at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:295)
        at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:557)
        at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:679)
        at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:727)
        at akka.actor.Actor.aroundPreStart(Actor.scala:528)
        at akka.actor.Actor.aroundPreStart$(Actor.scala:528)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:670)
        at akka.actor.ActorCell.create(ActorCell.scala:652)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:523)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:545)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[ERROR] [09/21/2018 08:53:32.024] [borsuk-akka.actor.default-dispatcher-9] [akka://borsuk/system/StreamSupervisor-0/flow-3-0-ignoreSink] Error during preStart in [akka.http.scaladsl.model.HttpEntity$Limitable@57ae4e0e]: EntityStreamSizeException: actual entity size (Some(11933835)) exceeded content length limit (8388608 bytes)! You can configure this by setting `akka.http.[server|client].parsing.max-content-length` or calling `HttpEntity.withSizeLimit` before materializing the dataBytes stream.
EntityStreamSizeException: actual entity size (Some(11933835)) exceeded content length limit (8388608 bytes)! You can configure this by setting `akka.http.[server|client].parsing.max-content-length` or calling `HttpEntity.withSizeLimit` before materializing the dataBytes stream.
        at akka.http.scaladsl.model.HttpEntity$Limitable$$anon$1.preStart(HttpEntity.scala:612)
        at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:295)
        at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:557)
        at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:679)
        at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:727)
        at akka.actor.Actor.aroundPreStart(Actor.scala:528)
        at akka.actor.Actor.aroundPreStart$(Actor.scala:528)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:670)
        at akka.actor.ActorCell.create(ActorCell.scala:652)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:523)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:545)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`

possible solution is to use function withoutSizeLimit(), example: 
Unmarshal(dataResponse.get.entity.**withoutSizeLimit()**)
But I am not sure, you gotta check it.

**Comment by wenta** [comment]
`withSizeLimit` exist to [avoid DoS attacks.](https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/misc-directives/withSizeLimit.html) 
I see two solutions: 
1. Return info that series in payload is too big to handle (so on client side additional action [like resampling] should be made)
2. Allow series with any sizes. 
Which one is better?

**Comment by tpichlak** [comment]
If timeseries has already option like resampling that could be done easy, then first option seems more reasonable.

**Comment by tpichlak** [comment]
I am having second thoughts about it. Maybe this restriction should be remove since we don't know if resampling does not affect the models and it seems also that if we want to avoid DoS attacks, than we'll probably develop another app for it.
